---
title: "toronto-crime"
author: "Shirley Chen"
format: html
editor: visual
---

```{r}
#| include: false
### Workspace Setup ###
library(tidyverse)
library(janitor)
library(opendatatoronto)
library(ggplot2)
library(knitr)
library(usethis)
library(gitcreds)
library(kableExtra)
```

```{r}
#| echo: false
raw_crime_data <- 
  read_csv(
    file = 
      "major-crime-indicators.csv",
    show_col_types = FALSE,
    skip = 0
  )

cleaned_crime_data <-
  clean_names(raw_crime_data)

# Remove unecessary columns
  cleaned_crime_data <-
    subset(cleaned_crime_data, select = -c(id, event_unique_id, report_date,
                                           report_year, report_month,
                                           report_day, report_doy,
                                           report_hour, hood_158,
                                           report_dow,occ_date, offence,
                                           ucr_code,ucr_ext, hood_140,
                                           division, neighbourhood_140))
# Keep years 2019-2023
  selected_years <- c("2019", "2020", "2021", "2022", "2023")
  cleaned_crime_data <- cleaned_crime_data |>
    filter(occ_year %in% selected_years)
  
# Rename columns to better understand
  cleaned_crime_data <- cleaned_crime_data |>
    rename(
      year = occ_year,
      month = occ_month,
      day = occ_day,
      day_of_year = occ_doy,
      day_of_week = occ_dow,
      hour_of_occurrence = occ_hour, 
      offence_type = mci_category
    )
  
# Incidents per year graph
  yearly_data <- cleaned_crime_data |>
    group_by(year) |>
    summarise(Incidents = n()) |>
    arrange(year)
  ggplot(yearly_data, aes(x = as.factor(year), y = Incidents)) +
    geom_bar(stat = "identity", fill = "skyblue") +
    labs(title = "Number of Incidents by Year (2019-2023)",
         x = "Year",
         y = "Number of Incidents")

```

```{r}
#| echo: false
# Incidents by the day of the week
  weekly_data <- cleaned_crime_data |>
    group_by(day_of_week) |>
    summarise(Incidents = n())
  
  week_order <- c("Sunday", "Monday", "Tuesday", "Wednesday",
                    "Thursday", "Friday","Saturday")
  weekly_data$day_of_week <- factor(weekly_data$day_of_week, 
                                 levels = week_order,
                                 ordered = TRUE)
  
  kable(weekly_data,
      col.names = c("Day of the Week", "Number of Incidents"),
      caption = "Number of Incidents by Day of the Week") |>
    kable_styling(full_width = FALSE)
  
  ggplot(weekly_data, aes(
    x = as.factor(day_of_week),
    y = Incidents)) +
    geom_bar(stat = "identity", fill = "skyblue") +
    labs(title = "Number of Incidents by Weekday (2019-2023)",
         x = "Day of the Week",
         y = "Number of Incidents")
```

```{r}
#| echo: false
# Incidents by offence type
  offence_data <- cleaned_crime_data |>
    group_by(offence_type) |>
    summarise(Incidents = n()) |>
    arrange(offence_type)
  
  ggplot(offence_data, aes(
    x = as.factor(offence_type),
    y = Incidents)) +
    geom_bar(stat = "identity", fill = "skyblue") +
    labs(title = "Number of Incidents by Offence (2019-2023)",
         x = "Offence Type",
         y = "Number of Incidents")
```

```{r}
#| echo: false
# Areas with least and most offences
  most_least_area_data <- cleaned_crime_data |>
    group_by(neighbourhood_158) |>
    summarise(Incidents = n()) |>
    arrange(desc(Incidents))
  
  most_data <- head(most_least_area_data, 5)
  descending_order <- c("West Humber-Clairville", "Moss Park", 
                        "Downtown Yonge East", "York University Heights",
                        "Yonge-Bay Corridor")
  most_data$neighbourhood_158 <- factor(most_data$neighbourhood_158, 
                                 levels = descending_order)
  
  least_data <- tail(most_least_area_data, 5)
  ascending_order <- c("Woodbine-Lumsden", "Guildwood", "Lambton Baby Point",
                       "Humber Heights-Westmount", "Old East York")
  least_data$neighbourhood_158 <- factor(least_data$neighbourhood_158, 
                                 levels = ascending_order)
  
  # Most incidents of crime
  ggplot(most_data, aes(
    x = as.factor(neighbourhood_158),
    y = Incidents)) +
    geom_bar(stat = "identity", fill = "skyblue") +
    labs(title = "Number of Incidents by Offence (2019-2023)",
         x = "Offence Type",
         y = "Number of Incidents") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  # Least incidents of crime
  ggplot(least_data, aes(
    x = as.factor(neighbourhood_158),
    y = Incidents)) +
    geom_bar(stat = "identity", fill = "skyblue") +
    labs(title = "Number of Incidents by Offence (2019-2023)",
         x = "Offence Type",
         y = "Number of Incidents") +
    theme(axis.text.x = element_text(size = 7, angle = 30, hjust = 1))
```
